export const CHANGE_INPIUT_VALUE = 'change_input_value'
export const ADD_TODO_LIST = 'add_todo_item'
export const DELETE_TODO_LIST = 'delete_todo_item'
export const INIT_LIST_ACTION = 'init_list_action'
export const GET_ININ_LIST = 'get_init_list'